services:
  zookeeper:
    image: bitnami/zookeeper
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - jaeger-network

  kafka:
    image: bitnami/kafka:3.9.0
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    restart: always
    depends_on:
      - zookeeper
    networks:
      - jaeger-network
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --list --bootstrap-server 127.0.0.1:9092"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./configs/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4318:4318"
    depends_on:
      - jaeger
    networks:
      - jaeger-network

  rabbitmq:
    image: rabbitmq:3.13.7-management
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=certifier
      - RABBITMQ_DEFAULT_PASS=relari
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - jaeger-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s

  jaeger:
    image: jaegertracing/jaeger:2.3.0
    ports:
      - "16686:16686"
      - "4317:4317"
      - "14318:4318"
      - "5778:5778"
      - "9411:9411"
    volumes:
      - ./configs/config-kafka-collector.yaml:/jaeger/config.yaml
      - ./configs/config-ui.json:/jaeger/config-ui.json
    environment:
      - OTEL_TRACES_SAMPLER=always_off
    command:
      - "--config"
      - "/jaeger/config.yaml"
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - jaeger-network
    
networks:
  jaeger-network:
    driver: bridge

volumes:
  rabbitmq_data:
